language: python
dist: xenial
python:
    - '3.6'
    - '3.7'
    - '3.7-dev'
    - '3.8-dev'
matrix:
    allow_failures:
        - python: 3.7-dev
        - python: 3.8-dev
before_install:
- pip install poetry
install:
- poetry install -v
- pip install tox-travis
script:
- export
- tox